#!/bin/bash

USER="lincolnbrito"
TIMESTAMP=$(date "+%Y%m%d%H%M")

echo "Building image ${USER}/cakephp-php7.2apache:${TIMESTAMP}..."
docker build -t ${USER}/cakephp-php7.2apache:${TIMESTAMP}.

echo "Tagging..."
docker tag ${USER}/cakephp-php7.2apache:${TIMESTAMP} ${USER}/cakephp-php7.2apache:latest

echo "Pushing image to docker cloud service"
docker push ${USER}/cakephp-php7.2apache:${TIMESTAMP}
docker push ${USER}/cakephp-php7.2apache:latest
