#!/bin/bash

USER="lincolnbrito"
TIMESTAMP=$(date "+%Y%m%d%H%M")

echo "Building image ${USER}/cakephp-php7.2fpm:${TIMESTAMP}..."
docker build -t ${USER}/cakephp-php7.2fpm:${TIMESTAMP} .

echo "Tagging..."
docker tag ${USER}/cakephp-php7.2fpm:${TIMESTAMP} ${USER}/cakephp-php7.2fpm:latest

echo "Pushing image to docker cloud service"
docker push ${USER}/cakephp-php7.2fpm:${TIMESTAMP}
docker push ${USER}/cakephp-php7.2fpm:latest
